services:
  db:
    image: postgres:17
    container_name: "database-JLF"
    environment:
      - POSTGRES_USER=JLF
      - POSTGRES_PASSWORD=contraseñaresegura
      - POSTGRES_DB=Queuee
    ports:
      - 5432:5432
    volumes:
      - ./tp2_dbdata:/var/lib/postgresql/data
